import type { Metadata } from 'next'
import './globals.css'
import { roboto } from '@/lib/fonts'
import clsx from 'clsx'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, "bg-amber-200 text-amber-900")}>
        <main className="max-w-xl m-auto mt-4 flex flex-col gap-2">
          {children}
        </main>
      </body>
    </html>
  )
}
